=== TheMentalTaco/genloc/schema/npc.schema.JSON
{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "title": "NPCSchema",
  "type": "object",

  "required": [
    "category",
    "name",
    "title",
    "location",
    "species",
    "languages",
    "base_desc",
    "age",
    "life_status",
    "pronouns",
    "equipment",
    "appearance_desc",
    "personality_desc",
    "affiliations",
    "player_visible"
  ],

  "properties": {
    "category": {
      "type": "string",
      "const": "NPC"
    },
    "name": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "location": {
      "type": "string"
    },
    "species": {
      "type": "string"
    },
    "languages": {
      "type": "array",
      "items": { "type": "string" }
    },
    "base_desc": {
      "type": "string"
    },
    "age": {
      "type": "integer",
      "minimum": 0
    },
    "life_status": {
      "type": "string"
    },
    "pronouns": {
      "type": "string"
    },
    "equipment": {
      "type": "array",
      "items": { "type": "string" }
    },
    "appearance_desc": {
      "type": "string"
    },
    "personality_desc": {
      "type": "string"
    },
    "affiliations": {
      "type": "object",
      "properties": {
        "org": { "type": "string" },
        "position": { "type": "string" },
        "org_status": { "type": "string" }
      }
    },
    "player_visible": {
      "type": "boolean"
    },
    "statblock": {
      "$ref": "statblock.schema.JSON"
    }
  }
}

=== TheMentalTaco/genloc/npcs/arlen.JSON
{
  "$schema": "../schema/npc.schema.JSON",
  "category": "NPC",
  "name": "Arlen",
  "title": "Dreadnought",
  "location": "wreck",
  "species": "human",
  "languages": ["terran"],
  "base_desc": "New Color Group supervisor after Taldrik takes a leave of absence",
  "age": 62,
  "life_status": "Alive",
  "pronouns": "He/Him",
  "equipment": [
    "armor_coffin_suit",
    "util_auspex_scanner",
    "weapon_heavy_cannon"
  ],
  "appearance_desc": "Arlen is paralyzed man in a giant suit of armor",
  "personality_desc": "Arlen is a gruff and stoic individual, often keeping to himself. He has a strong sense of duty",
  "affiliations": {
    "org": "corp_bluestar",
    "position": "Supervisor",
    "org_status": "Active"
  },
  "player_visible": true,

  "statblock": {
    "name": "Arlen",
    "type": "Humanoid",
    "ac": 17,
    "max_hp": 147,
    "current_hp": 147,
    "temp_hp": 0,
    "speed": {
      "walk": 30,
      "fly": 90,
      "swim": 0,
      "climb": 0,
      "burrow": 0
    },
    "stats": {
      "str": 24,
      "dex": 11,
      "con": 19,
      "int": 10,
      "wis": 10,
      "cha": 3
    },
    "dmg_res": ["Radiant"],
    "dmg_vuln": [],
    "dmg_immune": ["Cold", "Poison"],
    "conditions_immune": [
      "Charmed",
      "Exhaustion",
      "Frightened",
      "Paralyzed",
      "Petrified",
      "Poisoned"
    ],
    "bps": ["resistance", "nonmagical"],
    "cr": 11,
    "traits": [
      {"Immutable Form": "Arlen is immune to any spell or effect that would alter his form."}
    ],
    "actions": [ 
      {"Multiattack": "Arlen uses his Malevolent Prescence. He then makes three attacks: two with his fists and one with his heavy cannon. If Arlen hasn't moved this turn, he can make on additional attack with his heavy cannon."}    
      ]
  }
}
