=== TheMentalTaco/genloc/schema/species.schema.JSON
{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "title": "SpeciesSchema",
  "type": "object",

  "required": [
    "name",
    "origin",
    "base_desc",
    "appearance_desc",
    "size",
    "speed",
    "features"
  ],

  "properties": {
    "name": {
      "type": "string"
    },
    "origin": {
      "type": "string"
    },
    "base_desc": {
      "type": "string"
    },
    "appearance_desc": {
      "type": "string"
    },
    "size": {
      "type": "string"
    },
    "speed": {
      "type": "string"
    },
    "features": {
      "type": "array",
      "properties": {
        "name" : {"type": "string"}
      }
    }
  }
}

=== TheMentalTaco/genloc/species/human.json
{
  "$schema": "../schema/species.schema.JSON",
  "name" : "Human",
  "origin" : "Earth",
  "base_desc" : "Originated from Earth and Umperias experts in genetic modification and military technology. One of the most diverse species as they are the least united species. Give allegiances to corporations more than governments",
  "appearance_desc" : "You know what they can look like",
  "size" : "2-7 feet tall",
  "speed": "30 feet",
  "features" : [
      {"Resourceful" : "You gain Heroic Inspiration whenever you finish a Long Rest"},
      {"Skillful" : "You gain proficiency in one skill of your choice"},
      {"Versatile" : "You gain an Origin Feat of your choice"}
  ]
}
